name: egdata_flutter
description: "EGData Client - Epic Games manifest uploader"
publish_to: "none"
version: 1.0.13
environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  http_parser: ^4.0.2
  shared_preferences: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.9.0
  intl: ^0.19.0
  file_picker: ^8.0.0
  tray_manager: ^0.5.2
  window_manager: ^0.5.1
  launch_at_startup: ^0.5.1
  windows_single_instance: ^1.1.0
  table_calendar: ^3.1.2
  flutter_local_notifications: ^19.0.0
  url_launcher: ^6.3.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  package_info_plus: ^9.0.0
  cached_network_image: ^3.4.1
  firebase_core: ^3.9.0
  firebase_messaging: ^15.2.0
  fluquery: ^1.3.3
  firebase_analytics: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.12
  flutter_launcher_icons: ^0.14.4
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.0
  inno_bundle: ^0.11.2

flutter_launcher_icons:
  windows:
    generate: true
    image_path: assets/logo.png
    icon_size: 256
  android: true
  ios: true
  image_path: assets/logo.png
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/tray_icon.png
    - assets/tray_icon.ico
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf

msix_config:
  display_name: egdata.app
  publisher_display_name: Ignacio Aldama Vicente
  identity_name: IgnacioAldamaVicente.egdata.app
  publisher: CN=D9F4560B-64F8-46C1-AB63-C46F5454F331
  msix_version: 1.0.13.0
  capabilities: internetClient
  languages: en-us
  store: true
  logo_path: assets/logo.png
  icons_background_color: "#121212"

inno_bundle:
  id: ab497711-5d34-47ed-8d75-b0b70e1c7cd6
  name: egdata.app
  version: 1.0.13
  publisher: Ignacio Aldama Vicente
  languages:
    - english
    - french
    - german
    - spanish
    - portuguese
    - italian
    - dutch
    - polish
    - russian
    - japanese
    - turkish
